project_name: vogelkop
before:
  hooks:
    - go mod download

builds:
  -
    id: go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    ldflags:
      - -s -w
      - -X go.hollow.sh/toolbox/version.appName={{.ProjectName}}
      - -X go.hollow.sh/toolbox/version.version={{.Version}}
      - -X go.hollow.sh/toolbox/version.commit={{.Commit}}
      - -X go.hollow.sh/toolbox/version.date={{.Date}}
      - -X go.hollow.sh/toolbox/version.builtBy=goreleaser

archives:
  -
    id: go
    format: tar.gz
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
    files:
      - README.md

snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  -
    image_templates:
      - "ghcr.io/metal-toolbox/{{.ProjectName}}:{{ .Tag }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false


release:
    disable: false
    draft: false