project_name: vogelkop
before:
  hooks:
    - go mod download

builds:
  - id: vogelkop
    binary: vogelkop
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w
      - -X github.com/metal-toolbox/version.appName={{.ProjectName}}
      - -X github.com/metal-toolbox/version.version={{.Version}}
      - -X github.com/metal-toolbox/version.commit={{.Commit}}
      - -X github.com/metal-toolbox/version.date={{.Date}}
      - -X github.com/metal-toolbox/version.builtBy=goreleaser

archives:
  - id: vogelkop

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{.Tag}}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - "sign-blob"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "--yes"
      - "${artifact}"
    artifacts: all
    output: true

sboms:
  - artifacts: archive
  - id: source
    artifacts: source

release:
  disable: false
  draft: false
