name: goreleaser

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golangci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
          args: "--timeout=5m --out-${NO_FUTURE}format colored-line-number"
